### ISSUE TITLE
Error in show bytes resuts

### ISSUE THREAD

**Issue by OoHerbethoO** [alashow/datmusic-api#20] opened 2017-05-13 02:28 UTC
Hello, I am having a problem with the page of "bytes". The page you're returning the error "404", as shown in the screenshot.
![screenshot_2017-05-12-23-21-37](https://cloud.githubusercontent.com/assets/16544588/26021770/0990d4b0-376b-11e7-841d-ea8a347d2b9d.png)

**Comment by alashow** [comment] 2017-05-13 03:02
The cause might be 75fb34635ffffadf91c2a0861e0ae517ded893f7 which I fixed in 9b8fb5311f4b25520a3f3dcf43a78ef00eb03245

**Closed as completed** 2017-05-17 13:22 UTC
