### ISSUE TITLE
different search results

### ISSUE THREAD

**Issue by SerhiiMatvieiev** [alashow/datmusic-api#49] opened 2017-08-31 05:35 UTC
Hi, how it's possible when I try to search audios I get a completely different result in response?
Foe example, when i do something like this: http://mysite.xyz/search?q=linkin , i get result:

{"status":"ok","data":[{"artist":"Linkin Park and Kiiara","title":"Heavy (feat. Kiiara)","duration":169,"download":"http:\/\/mysite.xyz\/dl\/8600f8de\/88c7a71d","stream":"http:\/\/mysite.xyz\/stream\/8600f8de\/88c7a71d"},{"artist":"Charly Beck","title":"Burn It Down (feat. Linkin Park)","duration":193,"download":"http:\/\/mysite.xyz\/dl\/8600f8de\/539820a8","stream":"http:\/\/mysite.xyz\/stream\/8600f8de\/539820a8"},{"artist":"Instrumental All Stars","title":"Breaking the Habit (Originally Perfomed By Linkin Park)","duration":195,"download":"http:\/\/mysite.xyz\/dl\/8600f8de\/ac0066a3","stream":"http:\/\/mysite.xyz\/stream\/8600f8de\/ac0066a3"},{"artist":"Anne-Caroline Joy","title":"Heavy (Linkin Park Tribute)","duration":165,"download":"http:\/\/mysite.xyz\/dl\/8600f8de\/54807b36","stream":"http:\/\/mysite.xyz\/stream\/8600f8de\/54807b36"},{"artist":"Karaoke Jam Band","title":"Papercut (Karaoke Version) [Originally Performed by Linkin Park]","duration":186,"download":"http:\/\/mysite.xyz\/dl\/8600f8de\/d912f2aa","stream":"http:\/\/mysite.xyz\/stream\/8600f8de\/d912f2aa"}]}

But if i use https://datmusic.xyz/?q=linkin the result much better.

What do you think ?
Thanks!

**Comment by alashow** [comment] 2017-08-31 05:42
Duplicate of #35.

BTW, don't expose your site's URL (see #45).

**Closed as completed by alashow** 2017-08-31 05:42 UTC

**Comment by SerhiiMatvieiev** [comment] 2017-08-31 06:12
thanks, so i need to setup proxy config?
# proxy config
PROXY_ENABLE=true
PROXY_IP=
PROXY_PORT=80
PROXY_USERNAME=
PROXY_PASSWORD=

maybe you know where i can get russian proxy ?

**Comment by alashow** [comment] 2017-08-31 06:33
As @sy2nyk suggested [here](https://github.com/alashow/datmusic-api/issues/35#issuecomment-321979628), I used [veesp.com](https://veesp.com) for proxy server.

You could start from Sandbox (1TB bandwidth limit), then upgrade to SSD 1 (unlimited badnwidth) if you exceed the limit.
You could use my referral link https://secure.veesp.com/?affid=286 (will redirect to SSDs).

Then install squid proxy:
```bash
apt-get update
apt-get install squid
```

To verify installation:
```
squid -h
```

Then edit config:
```yaml
http_port 9091

# replace with your ip
acl client src 88.99.184.30
http_access allow client

forwarded_for off
request_header_access Allow allow all
request_header_access Authorization allow all
request_header_access WWW-Authenticate allow all
request_header_access Proxy-Authorization allow all
request_header_access Proxy-Authenticate allow all
request_header_access Cache-Control allow all
request_header_access Content-Encoding allow all
request_header_access Content-Length allow all
request_header_access Content-Type allow all
request_header_access Date allow all
request_header_access Expires allow all
request_header_access Host allow all
request_header_access If-Modified-Since allow all
request_header_access Last-Modified allow all
request_header_access Location allow all
request_header_access Pragma allow all
request_header_access Accept allow all
request_header_access Accept-Charset allow all
request_header_access Accept-Encoding allow all
request_header_access Accept-Language allow all
request_header_access Content-Language allow all
request_header_access Mime-Version allow all
request_header_access Retry-After allow all
request_header_access Title allow all
request_header_access Connection allow all
request_header_access Proxy-Connection allow all
request_header_access User-Agent allow all
request_header_access Cookie allow all
request_header_access All deny all
```
Restart squid:
```bash
service squid status
```
Or, you could just use VPS from veesp.com and use it as your main server for datmusic-api.

**Comment by SerhiiMatvieiev** [comment] 2017-08-31 07:36
Thank you so much !
